deployments:
  - include: ../../modules/nginx
    vars:
      - values:
          config:
            namespace: "test"
            version: "20.0.8"
            nginx_values:
              image:
                repository: "nginx"
                tag: "1.21.6"
              service:
                type: "LoadBalancer"
                port: 80
              resources:
                limits:
                  cpu: "500m"
                  memory: "512Mi"
